# Generated by Django 5.1.1 on 2024-10-14 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0006_chat_chathistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_bot.customuser'),
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
